use_frameworks!

platform :ios, '10.0'

target 'MFBubbleAnimator_Example' do
  pod 'MFBubbleAnimator', :path => '../'

  target 'MFBubbleAnimator_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
